"""empty message

Revision ID: 92dc9349a323
Revises: 0d6b29c7473a
Create Date: 2020-03-21 22:43:23.065218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92dc9349a323'
down_revision = '0d6b29c7473a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_data_dict_dict_type'), 'data_dict', ['dict_type'], unique=False)
    op.add_column('users', sa.Column('avatar_url', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('user_type', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('wechat_avatar', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('wechat_city', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('wechat_country', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('wechat_gender', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('wechat_language', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('wechat_nickname', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('wechat_openid', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('wechat_privilege', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('wechat_province', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('wechat_union_id', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_users_wechat_openid'), 'users', ['wechat_openid'], unique=False)
    op.drop_column('users', 'openid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('openid', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_wechat_openid'), table_name='users')
    op.drop_column('users', 'wechat_union_id')
    op.drop_column('users', 'wechat_province')
    op.drop_column('users', 'wechat_privilege')
    op.drop_column('users', 'wechat_openid')
    op.drop_column('users', 'wechat_nickname')
    op.drop_column('users', 'wechat_language')
    op.drop_column('users', 'wechat_gender')
    op.drop_column('users', 'wechat_country')
    op.drop_column('users', 'wechat_city')
    op.drop_column('users', 'wechat_avatar')
    op.drop_column('users', 'user_type')
    op.drop_column('users', 'avatar_url')
    op.drop_index(op.f('ix_data_dict_dict_type'), table_name='data_dict')
    # ### end Alembic commands ###
