"""empty message

Revision ID: 146815beda19
Revises: 23674ff7ce13
Create Date: 2020-02-15 12:35:39.955175

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '146815beda19'
down_revision = '23674ff7ce13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('data_scope', sa.SmallInteger(), nullable=False))
    op.add_column('roles', sa.Column('web_menus', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'web_menus')
    op.drop_column('roles', 'data_scope')
    # ### end Alembic commands ###
