"""empty message

Revision ID: 0d6b29c7473a
Revises: bb51936ae160
Create Date: 2020-03-18 21:21:50.626139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0d6b29c7473a'
down_revision = 'bb51936ae160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_dict', sa.Column('sort_number', sa.Integer(), autoincrement=True, nullable=True))
    op.alter_column('data_dict', 'update_date',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    op.create_index(op.f('ix_data_dict_sort_number'), 'data_dict', ['sort_number'], unique=False)
    op.add_column('offices', sa.Column('sort_number', sa.Integer(), autoincrement=True, nullable=True))
    op.alter_column('offices', 'update_date',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    op.create_index(op.f('ix_offices_sort_number'), 'offices', ['sort_number'], unique=False)
    op.add_column('roles', sa.Column('sort_number', sa.Integer(), autoincrement=True, nullable=True))
    op.alter_column('roles', 'update_date',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    op.create_index(op.f('ix_roles_sort_number'), 'roles', ['sort_number'], unique=False)
    op.add_column('user_role', sa.Column('sort_number', sa.Integer(), autoincrement=True, nullable=True))
    op.alter_column('user_role', 'update_date',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    op.create_index(op.f('ix_user_role_sort_number'), 'user_role', ['sort_number'], unique=False)
    op.add_column('users', sa.Column('sort_number', sa.Integer(), autoincrement=True, nullable=True))
    op.alter_column('users', 'update_date',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    op.create_index(op.f('ix_users_sort_number'), 'users', ['sort_number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_sort_number'), table_name='users')
    op.alter_column('users', 'update_date',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    op.drop_column('users', 'sort_number')
    op.drop_index(op.f('ix_user_role_sort_number'), table_name='user_role')
    op.alter_column('user_role', 'update_date',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    op.drop_column('user_role', 'sort_number')
    op.drop_index(op.f('ix_roles_sort_number'), table_name='roles')
    op.alter_column('roles', 'update_date',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    op.drop_column('roles', 'sort_number')
    op.drop_index(op.f('ix_offices_sort_number'), table_name='offices')
    op.alter_column('offices', 'update_date',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    op.drop_column('offices', 'sort_number')
    op.drop_index(op.f('ix_data_dict_sort_number'), table_name='data_dict')
    op.alter_column('data_dict', 'update_date',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    op.drop_column('data_dict', 'sort_number')
    # ### end Alembic commands ###
