"""empty message

Revision ID: 23674ff7ce13
Revises: 1d3b222125a3
Create Date: 2020-02-15 12:05:06.826011

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '23674ff7ce13'
down_revision = '1d3b222125a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offices', sa.Column('parent_id', postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, 'offices', 'offices', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offices', type_='foreignkey')
    op.drop_column('offices', 'parent_id')
    # ### end Alembic commands ###
