"""empty message

Revision ID: 0a74fb083ef4
Revises: 49e93ddf4f95
Create Date: 2020-02-15 18:08:51.947904

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a74fb083ef4'
down_revision = '49e93ddf4f95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_dict',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('remarks', sa.String(length=128), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('create_by', sa.String(length=64), nullable=True),
    sa.Column('update_by', sa.String(length=64), nullable=True),
    sa.Column('dict_value', sa.String(length=64), nullable=True),
    sa.Column('dict_label', sa.String(length=64), nullable=True),
    sa.Column('dict_description', sa.String(length=256), nullable=True),
    sa.Column('dict_type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_dict')
    # ### end Alembic commands ###
