"""empty message

Revision ID: bb51936ae160
Revises: 0a74fb083ef4
Create Date: 2020-02-26 19:27:17.472035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb51936ae160'
down_revision = '0a74fb083ef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_dict', sa.Column('dict_key', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_data_dict_dict_key'), 'data_dict', ['dict_key'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_dict_dict_key'), table_name='data_dict')
    op.drop_column('data_dict', 'dict_key')
    # ### end Alembic commands ###
